SELECT ?simpleBind ?simpleUriBind ?simpleIriBind ?uri_string  ?uri_int ?uri_undef  ?uri_undef2 ?coalesce  ?uri_string_coalesce WHERE  {
    VALUES ?undef {UNDEF}
    BIND("test" as ?simpleBind)
    BIND(<test:uri> as ?simpleUriBind)
    BIND(IRI("test:uri") as ?simpleIriBind)
    BIND(IF(true, <test:uri>, "testString") as ?uri_string) 
    BIND(IF(true, <test:uri>, 1.0) as ?uri_int) 
    BIND(IF(true, <test:uri>, ?undef) as ?uri_undef) 
    BIND(IF(true, <test:uri>, 1/0) as ?uri_undef2)
    BIND(COALESCE(?undef, "test") as ?coalesce)
    BIND(IF(true, COALESCE(?undef, <test:uri>), "testString") as ?uri_string_coalesce) 
}