SELECT ?includes ?included WHERE {
    # Get entities included in another
    ?included a <test:tab>  .
    ?includes a <test:tab>  .
  	FILTER (?included != ?includes )
    FILTER NOT EXISTS {
  		?included <test:prop1> ?bn1 .
        ?bn1 <test:prop2> ?obj1 .
        ?bn1 <test:prop3> ?obj2 .
        FILTER NOT EXISTS {
    		?includes <test:prop1> ?bn2 .
            ?bn2 <test:prop2> ?obj1 .
            ?bn2 <test:prop3> ?obj2 .
        }
    }
}
