# Since graphDb seems to join from outside in, the outer graph pattern cannot constrain the inner pattern with only a subselect (because it has already been evaluated)
# Adding a BGP to the inner pattern containing the joining variable makes graphdb reevaluate the inner pattern and give the right results
SELECT ?b ?c WHERE {
    ?b <test:prop2> ?c
    FILTER NOT EXISTS {
            ?b a <test:class>.
            {
                SELECT ?b WHERE {
                   ?a <test:prop1> ?b
                }
     		}
    }
}