// tag::body[]

== Get started

Instanciate the project https://github.com/Semantic-partners/mustrd-template[mustrd-template]. It contains the basic configuration to get mustrd running.

Clone the created repo in local.

== Edit the triple store configuration

If you just want to use embedded RDFlib, you don't need to change anything.

If you want to use an external triplestore such as Anzo or graphDB, you have to define some basic parameters.

The default triplestore config file is https://github.com/Semantic-partners/mustrd-template/blob/main/test/triplestore_config/triplestores.ttl[here]

You can store your passwords in another https://github.com/Semantic-partners/mustrd-template/blob/main/test/triplestore_config/triplestores_secrets.ttl[file] at the same location and same name suffixed with "_secrets".

For example passwords of triplestores configured in [repo_root]/test/triplestore_config/triplestores.ttl have to be stored in the file [repo_root]/test/triplestore_config/triplestores_secrets.ttl

By default .gitignore is configured so you don't commit the secrets files, while the triplestore configuration files will be commited, so be sure to store your secrets in the separated _secrets file.

To associate a triplestore configuration and its secrets, use the same subject in configuration and secret file, like it is done in the example.

Triplestore configuration can be placed anywhere, inside our outside of your project, but it has to be referenced in the test configuration.

== Edit Test configuration

In the template project, the default test configuration is located https://github.com/Semantic-partners/mustrd-template/blob/main/test/local_configuration.ttl[here] 

In that file you can define different test that mustrd will run when you give that file as parameter of mustrd pytest plugin

----
// tag::body[]