= MustRD Documentation
:toc: left
:toclevels: 3

== Introduction

MustRD is a framework for testing SPARQL queries against RDF datasets. It supports embedded RDFLib and external triplestores like Anzo and GraphDB. This documentation provides a comprehensive guide to using MustRD effectively.

It is a pytest plugin, and can be activated by adding `--mustrd` to the pytest command line.

== Getting Started

=== Project Setup

You need a Python virtual environment (version [3.11, 3.12)) with MustRD installed.

[source]
----
source .venv/bin/activate
pip install mustrd
----

Examples of how to configure MustRD for VS Code can be found in the README.md file.

=== Initial Configuration

If you only need embedded RDFLib, no additional configuration is required.

For external triplestores such as Anzo or GraphDB, you must specify the connection details.

Examples of configuration files are available in the MustRD repository: https://github.com/Semantic-partners/mustrd/blob/master/test/test-mustrd-config/test_mustrd_simple.ttl

If your triplestore (e.g., Anzo or GraphDB) requires authentication, credentials should be stored in a separate file to avoid committing sensitive information to version control. The secrets file must have the same name as the triplestore configuration file, with the suffix `_secrets`. For example, if your triplestore configuration file is `/test/triplestore_config/triplestores.ttl`, the secrets file should be `/test/triplestore_config/triplestores_secrets.ttl`.

== Configuration

=== Triple Store Configuration

Passwords for triplestores configured in `/test/triplestore_config/triplestores.ttl` must be stored in `/test/triplestore_config/triplestores_secrets.ttl`.

By default, `.gitignore` is set up to prevent secrets files from being committed, while allowing triplestore configuration files to be committed. Ensure that secrets are stored in the `_secrets` file.

To associate a triplestore configuration with its secrets, use the same subject in both files, as shown in the example.

Triplestore configurations can be placed anywhere, inside or outside your project, but they must be referenced in the test configuration.

All triplestores must include a `url` property.

Additional mandatory properties depend on the triplestore:

==== For Anzo:

* `gqeURI` is required to identify the AnzoGraph where queries will be executed.
* `inputGraph` and `outputGraph` are mandatory because graphs cannot be created automatically on insert in Anzo. You must create a graphmart, add layers to it, and activate the graphmart.

==== For GraphDB:

* Only `repository` is mandatory. If `inputGraph` is not defined, all graphs in the repository will be queried.

=== Test Configuration

The default test configuration is located in the MustRD template project: https://github.com/Semantic-partners/mustrd-template/blob/main/test/mustrd_configuration.ttl

In this file, you can define various tests for MustRD to run when provided as a parameter to the MustRD pytest plugin.

For each test, you can configure:

* `hasSpecPath`: Folder containing MustRD specs (searches subfolders).
* `hasDataPath`: Folder for input/output data.
* `hasPytestPath`: Path in the test hierarchy.
* `triplestoreSpecPath`: Location of the external triplestore configuration file.
* `filterOnTripleStore`: List of triplestores defined in the configuration file (or RDFLib) to be used for the test.

Example:

----
:test_anzo a :MustrdTest;
            :hasSpecPath "test/test_examples/";
            :hasDataPath "test/test_data";
            :hasPytestPath "anzo";
            :triplestoreSpecPath "test/triplestore_config/triplestores.ttl";
            :filterOnTripleStore triplestore:anzo_test .
----

This configuration runs tests in `[project_root]/test/test_examples/`, using data from `[project_root]/test/test_data`, against the triplestore `triplestore:anzo_test` defined in `[project_root]/test/triplestore_config/triplestores.ttl`.

If required, secrets must be located in `[project_root]/test/triplestore_config/triplestores_secrets.ttl`.

== Run the Tests

After defining your triplestore(s) and MustRD test(s), you can run the default test specs in the MustRD template to verify your configuration.

Navigate to your repository's root folder and execute:

[source]
----
poetry run pytest --mustrd --config=test/mustrd_configuration.ttl --md=render/github_job_summary.md
----

This command uses poetry to run pytest with the MustRD plugin.

Parameters for the MustRD pytest plugin:

* `config`: MustRD test configuration file.
* `md`: Output location for the test execution summary.

Once the default tests are running successfully, you can define your own tests.

== Creating Your Own Test Specifications

If you've reached this point, you're ready to create your own specifications to test your application's SPARQL queries. These will be executed against the default RDFLib triplestore unless you configure alternatives. Instructions for this are included in <<Edit the triple store configuration>>.

=== Paths

All paths are considered relative, allowing MustRD tests to be versioned and shared easily.

To convert relative paths to absolute paths in a spec file, prefix them with the first existing result from:

. Path where the spec is located.
. `spec_path` defined in MustRD test configuration files or command-line arguments.
. `data_path` defined in MustRD test configuration files or command-line arguments.
. MustRD folder: Default resources packaged with MustRD source (in the virtual environment when MustRD is used as a library).

The same method is used to build paths across all spec components to avoid confusion.

=== Givens

These specify the dataset against which the SPARQL statement will be run. Datasets can be generated from external sources such as an existing graph, a file or folder containing serialized RDF, or reified RDF directly in the test step. Currently, tabular data sources like CSV files or TableDatasets are not supported.

Multiple given statements can be supplied, combining data into a single dataset for the test.

* *InheritedDataset*: Retains existing data in the target graph rather than replacing it with a defined set. Useful for chaining tests or checking application data.
----
    must:given [ a must:InheritedDataset ] ;
----
* *FileDataset*: Local file containing serialized RDF. Supported formats include Turtle (.ttl), NTriples (.nt), N3 (.n3), RDF/XML (.xml), and TriX. Replaces existing content in the target graph.
----
    must:given [ a must:FileDataset ;
                 must:file "test/data/given.ttl" . ] ;
----
* *FolderDataset*: Similar to FileDataset but the file location is passed as an argument from the caller (e.g., `-g` option on the command line).
----
    must:given [ a must:FolderDataset ;
                 must:fileName "given.ttl" ] ;
----
* *StatementsDataset*: Dataset defined within the test as reified RDF statements.
----
    must:given [ a must:StatementsDataset ;
                 must:hasStatement [ a rdf:Statement ;
                                     rdf:subject   test-data:sub ;
                                     rdf:predicate test-data:pred ;
                                     rdf:object    test-data:obj ; ] ; ] ;
----
* *AnzoGraphmartDataset*: Dataset contained in an Anzo graphmart. The Anzo instance must be specified in the configuration file.
----
    must:given [ a must:AnzoGraphmartDataset ;
                 must:graphmart "http://cambridgesemantics.com/Graphmart/43445aeadf674e09818c81cf7049e46a";
                 must:layer "http://cambridgesemantics.com/Layer/33b97531d7e148748b75e4e3c6bbf164";
    ] .
----
=== Whens
These are the actual SPARQL queries that you wish to test. Queries can be supplied as a string directly in the test or as a file containing the query. Only single When statements are currently supported.
Mustrd does not derive the query type from the actual query, so it is necessary to provide this in the specification. Supported query types are SelectSparql, ConstructSparql and UpdateSparql.

* *TextSparqlSource* - The SPARQL query is included in the test as a (multiline) string value for the property queryText.
e.g.
----
    must:when  [ a must:TextSparqlSource ;
                 must:queryText "SELECT ?s ?p ?o WHERE { ?s ?p ?o }" ;
                 must:queryType must:SelectSparql ] ;
----

* *FileSparqlSource* - The SPARQL query is contained in a local file.
e.g.
----
    must:when  [ a must:FileSparqlSource  ;
                 must:file "test/data/construct.rq" ;
                 must:queryType must:ConstructSparql  ; ] ;
----
* *FolderSparqlSource* - Similar to the file SPARQL source except that the location of the file is passed to the test specification as an argument from the caller. i.e. the -w option on the command line.
----
    must:when  [ a must:FolderSparqlSource ;
                 must:fileName "construct.rq" ;
                 must:queryType must:ConstructSparql  ; ] ;
----
* *AnzoQueryBuilderDataset* - The query is saved in the Query Builder of an Anzo instance and needs to be retrieved from there. The Anzo instance containing the dataset needs to be indicated in the configuration file as documented in <<Edit the triple store configuration>>.
----
   must:when  [ a must:AnzoQueryBuilderDataset ;
                must:queryFolder "Mustrd";
                must:queryName "mustrd-construct" ;
                must:queryType must:ConstructSparql
    ];
----
=== Thens
Then clauses are used to specify the expected result dataset for the test. These datasets can be specified in the same way as <<Givens>> except that an extended set of dataset types is supported. For the tabular results of SELECT queries TabularDatasets are required and again can be in file format such as CSV, or an inline table within the specification.
* *FileDataset* - The dataset is a local file containing serialised RDF or tabular data. The formats supported are the same as those for the RDFLib Graph().parse function i.e. Turtle (.ttl), NTriples (.nt), N3 (.n3), RDF/XML (.xml) and TriX, as well as tabular formats (.csv, .xls, .xlsx).
----
    must:then  [ a must:FileDataset ;
                 must:file "test/data/thenSuccess.xlsx" ] .
----
----
    must:then  [ a must:FileDataset ;
                 must:file "test/data/thenSuccess.nt" ] .
----
* *FolderDataset* - Very similar to the file dataset except that the location of the file is passed to the test specification as an argument from the caller. i.e. the -t option on the command line.
----
    must:then [ a must:FolderDataset ;
                 must:fileName "then.ttl" ] ;
----
* *StatementsDataset* - The dataset is defined within the test in the form of reified RDF statements e.g.
----
    must:then [ a must:StatementsDataset ;
                 must:hasStatement [ a rdf:Statement ;
                                     rdf:subject   test-data:sub ;
                                     rdf:predicate test-data:pred ;
                                     rdf:object    test-data:obj ; ] ; ] ;
----
* *TableDataset* - The contents of the table defined in RDF syntax within the specification.
E.g. a table dataset consisting of a single row and three columns.
----
    must:then  [ a must:TableDataset ;
                   must:hasRow [ must:hasBinding[
                        must:variable "s" ;
                        must:boundValue  test-data:sub ; ],
                      [ must:variable "p" ;
                        must:boundValue  test-data:pred ; ],
                      [ must:variable "o" ;
                        must:boundValue  test-data:obj ; ] ;
               ] ; ] .
----
* *OrderedTableDataset* -  This is an extension of the TableDataset which allows the row order of the dataset to be specified using the SHACL order property to support the ORDER BY clause in SPARQL SELECT queries
E.g. A table dataset consisting of two ordered rows and three columns.
----
    must:then  [ a must:OrderedTableDataset ;
                 must:hasRow [ sh:order 1 ;
                             must:hasBinding[ must:variable "s" ;
                                        must:boundValue  test-data:sub1 ; ],
                                      [ must:variable "p" ;
                                        must:boundValue  test-data:pred1 ; ],
                                      [ must:variable "o" ;
                                        must:boundValue  test-data:obj1 ; ] ; ] ,
                            [ sh:order 2 ;
                             must:hasBinding[ must:variable "s" ;
                                        must:boundValue  test-data:sub2 ; ],
                                      [ must:variable "p" ;
                                        must:boundValue  test-data:pred2 ; ],
                                      [ must:variable "o" ;
                                        must:boundValue  test-data:obj2 ; ] ; ] ;
               ] .
----
* *EmptyTable* - This is used to indicate that we are expecting an empty result from a SPARQL SELECT query.
----
    must:then  [ a must:EmptyTable ] .
----
* *EmptyGraph* - Similar to EmptyTable but used to indicate that we are expecting an empty graph as a result from a SPARQL query.
----
    must:then  [ a must:EmptyGraph ] .
----
* *AnzoGraphmartDataset* - The dataset is contained in an Anzo graphmart and needs to be retrieved from there. The Anzo instance containing the dataset needs to be indicated in the configuration file as documented in <<Edit the triple store configuration>>.
----
    must:then [ a must:AnzoGraphmartDataset ;
                must:graphmart "http://cambridgesemantics.com/Graphmart/43445aeadf674e09818c81cf7049e46a";
                must:layer "http://cambridgesemantics.com/Layer/33b97531d7e148748b75e4e3c6bbf164";
        ] .
----