// tag::body[]
== Get started
== Configuring external triplestores
The configuration file for external triplestores can be located outside of the project root as it is specified as an argument to the mustard module or as the -c option on the commandline when running run.py.

It is anticipated that the external triplestore is running as mustrd is not configured to start them.

Currently, the supported external triplestores are GraphDB and Anzo.

The configuration file should be serialised RDF. An example in Turtle format is included below for GraphDB. For Anzo the *must:repository* value is replaced with a *must:gqeURI*.
----
@prefix must:      <https://mustrd.com/model/> .
must:GraphDbConfig1  a must:GraphDbConfig ;
        must:url "http://localhost";
        must:port "7200";
        must:inputGraph "http://localhost:7200/test-graph" ;
        must:repository "mustrd" .
----
To avoid versioning secrets when you want to version triplestore configuration (for example in case you want to run mustrd in CI), you have to configure user/password in a different file.
This file must be named as the triple store configuration file, but with "_secrets" just before the extension. For example triplestores.ttl -> triplestores_secrets.ttl
Subjects in the two files must match, no need to redefine the type, for example:
----
@prefix must:      <https://mustrd.com/model/> .
must:GraphDbConfig1  must:username 'test' ;
              must:password 'test' .
----
// tag::body[]